```{r, message=FALSE}
library(ggraph) 
library(igraph)
library(cli)
library(dplyr)
library(tidyverse) 
library(data.tree) # for making the 'ontology' data structure
library(rlang)
library(networkD3) # for making interactive viz
library(htmltools)
library(stringr)  
```

```{r, message=FALSE}
# https://stackoverflow.com/questions/13673894/suppress-nas-in-paste
# function to remove NAs and change to ""
paste5 <- function(..., sep = " ", collapse = NULL, na.rm = F) {
  if (na.rm == F)
    paste(..., sep = sep, collapse = collapse)
  else
    if (na.rm == T) {
      paste.na <- function(x, sep) {
        x <- gsub("^\\s+|\\s+$", "", x)
        ret <- paste(na.omit(x), collapse = sep)
        is.na(ret) <- ret == ""
        return(ret)
      }
      df <- data.frame(..., stringsAsFactors = F)
      ret <- apply(df, 1, FUN = function(x) paste.na(x, sep))
      if (is.null(collapse))
        ret
      else {
        paste.na(ret, sep = collapse)
      }
    }
} 
```

### Inflammaging dataset
```{r}
#### Reshape Inflammaging df to conform to ontology 
inflam <- read.csv("inflammaging_varicat.csv", sep=",", header=TRUE)

colnames_inflam <- colnames(inflam) # get col names 
inflam_subset_cols <- colnames_inflam[lapply(colnames_inflam, function(x) length(grep("Please|Is.this|What" ,x,value=FALSE))) == 0] # remove sublevels that are too low in the tree
inflam <- inflam %>% dplyr::select(inflam_subset_cols) %>%  select(-(last_col(offset = 5):last_col()))  %>% 
  select(-head(names(.), 5)) # remove first and last five cols

inflam <- mutate_all(inflam, list(~na_if(.,""))) # remove "" and replace as NAs


#num_var_per_level <- data.frame(colSums(!is.na(inflam ))) # how many variables are there in each level? (e.g., in  Physical health -> Physical Measurements ->	Weight)
#num_var_per_level<- cbind(rownames(num_var_per_level), data.frame(num_var_per_level, row.names=NULL)) # remove row index, create row index as new col
#colnames(num_var_per_level) <- c("old_names", "num_var") # rename cols

inflam_2_cols <- cbind(inflam[1], mycol = do.call(pmax, c(inflam[-1], na.rm = TRUE))) %>% group_by(mycol) %>% arrange(Domain.Main.category.of.the.variable.) #collapse mult columns into 1
 

# inflam_subSet %>% dplyr::select(Comorbidities.type., Physical.health.type.) %>% filter(Physical.health.type. == "Comorbidities", !is.na(Comorbidities.type.)) # 120 vars
# inflam_subSet %>% dplyr::select(Comorbidities.type., Physical.health.type.) %>% filter(Physical.health.type. == "Comorbidities", is.na(Comorbidities.type.)) # 31 vars 

#inflam %>% group_by(Type.of.clinical.characteristics.) %>% filter(!is.na(Type.of.clinical.characteristics.)) %>%  select_if(~any(!is.na(.)))
#inflam %>% group_by(Course.of.bipolar.illness.symptoms.type.) %>% filter(!is.na(Course.of.bipolar.illness.symptoms.type.)) %>%  select_if(~any(!is.na(.))) %>% arrange(Course.of.bipolar.illness.symptoms.type.)
# redcap_output <-  read.csv("redcap_output_colnames.csv")
# l1_exist_in_inflam <- unique(redcap_output$level1)[unique(redcap_output$level1) %in% colnames(inflam)]
# l2_exist_in_inflam <- unique(redcap_output$level2)[unique(redcap_output$level2) %in% colnames(inflam)]
# l3_exist_in_inflam <- unique(redcap_output$level3)[unique(redcap_output$level3) %in% colnames(inflam)]
 
# unique(redcap_output$level1)
```



### Data cleaning for inflammaging dataset
```{r}
all_levels<-read.csv("all_levels_names.csv") 

# check level names in inflam dataset that do not belong to any levels ontology (this is weird, need to check)
inflam_2_cols[!inflam_2_cols$mycol %in% c(all_levels$level2) & 
                 !inflam_2_cols$mycol %in% c(all_levels$level3),] %>% group_by(mycol) %>% tally() 

inflam_2_cols <- inflam_2_cols [!inflam_2_cols$mycol %in% c("Drug name", "Miscellaneous", "Number of conditions", "Severity score"), ]

#inflam_2_cols%>% group_by(Domain.Main.category.of.the.variable., mycol) %>% tally()  #=== THIS IS CORRECT ====

inflam_2_cols <- inflam_2_cols %>% mutate(Domain.Main.category.of.the.variable.=  case_when(mycol == "Physical Measurements" & Domain.Main.category.of.the.variable. == "Physiological" ~ "Physical health", 
                                                                                            TRUE ~ Domain.Main.category.of.the.variable. ))   
 
# looks like these levels are actually level 4 categories -> remove them 
# group by level2 and 3 names and count the number vars in each of levels 
inflam <- inflam_2_cols[!inflam_2_cols$mycol %in% c("Drug name", "Miscellaneous", "Number of conditions", "Severity score"), ] %>% group_by(Domain.Main.category.of.the.variable., mycol) %>% dplyr::mutate(n= n()) %>%arrange(Domain.Main.category.of.the.variable.)  %>% distinct()

only_level_2 <- inflam[inflam$mycol %in%c(all_levels$level2), ]
only_level_3 <- inflam[inflam$mycol %in%c(all_levels$level3), ]

colnames(only_level_2) <- c("Domain", "level2", "level2_n")
colnames(only_level_3) <- c("Domain", "level3", "level3_n")
# separate level 2 and 3 into different columns
inflam_level_2_3_split <- rbind(only_level_2, only_level_3)

Current_diagnosis_sublevels <- c('Diagnostic group (e.g., Bipolar vs other psychiatric diagnosis or HC)',
  'Other diagnostic specifiers', 
  'Current episode type (e.g., manic/depressed/euthymic/mixed/remitted)', 
  'Most recent affective episode type')
global <- c('Global/screening score')
dep_eps_course <- c('History of psychotic depression', 'History of depression with atypical symptoms', 'Number of depressive episodes')
manic_eps_course <- c('Number of manic episodes')
hypomanic_eps_course <-  c('Number of hypomanic episodes')
mixed_eps_course <- c('Number of mixed episodes')
general_eps_features <- c('Lifetime rapid cycling', 'Seasonality?')
hopsitalizations <- c('Number of psychiatric hospitalizations')
functioning <- c('Rated by others')
c_drug_class <- c('Total psychiatric medications (count)',  'Non-Psychiatric Medications')
ect <- c('Lifetime number of ECTs')
phys_measure <- c('Weight')
comorbidities  <- c('Heart', 'Vascular', 'Renal','Endocrine and breast', 'Respiratory', 'Eyes/ears/ nose/ throat/ and larynx', 'Musculoskeletal and skin', 'Neurologic', 'Liver/pancreas/ and biliary', 'Upper GI','Lower GI', 'Hematopoietic', 'Genitourinary') 

inflam_level_2_3_split <- inflam_level_2_3_split %>% mutate(level2 = case_when(
  level3 %in% Current_diagnosis_sublevels  ~ "Current diagnosis", 
  level3 %in% global ~ "Global",
  level3 %in% dep_eps_course ~ "Depressive episode course",
  level3 %in% manic_eps_course ~ "Manic episode course",
  level3 %in% hypomanic_eps_course ~ "Hypomanic episode course",
  level3 %in% mixed_eps_course ~ "Mixed episode course",
  level3 %in% general_eps_features ~ "General episodic features",
  level3 %in% hopsitalizations ~ "Hopsitalizations",
  level3 %in% functioning ~ "Functioning",
  level3 %in% c_drug_class ~ "Drug class",
  level3 %in% ect ~ "ECT",
  level3 %in% phys_measure ~ "Physical Measurements",
  level3 %in% comorbidities ~ "Comorbidities",
  TRUE ~ level2))
```
### Hard-coding to prevent non-unique node names
```{r}
inflam_combined_n <- cbind(inflam_level_2_3_split[c(1,2,4)], mycol = do.call(pmax, c(inflam_level_2_3_split['level2_n'] , inflam_level_2_3_split['level3_n'], na.rm = TRUE))) %>% arrange(Domain)
inflam_combined_n <- inflam_combined_n %>% mutate(level2 = case_when(Domain == 'Current pharmacological treatment' & level3 == 'Total psychiatric medications (count)' ~ "Current Drug Class",
                                                Domain == 'Current pharmacological treatment' & level3 == 'Non-Psychiatric Medications' ~ "Current Drug Class",
                                                 Domain == 'Current pharmacological treatment' & level2 == 'Drug class' & is.na(level3) ~ "Current Drug Class",
                                                TRUE ~level2)) %>% mutate(level3 = case_when(
                                                  Domain == "Course of non-bipolar psychiatric illness" & level3 == 'Other' ~ "CoNBDpi Other",
                                                  Domain == "Metadata" & level3 == 'Other' ~ "Metadata Other",
                                                   Domain == "Current pharmacological treatment" & level3 == 'Other' ~ "C PT Other",
                                                   TRUE ~level3)) %>% mutate(level2 = case_when(
                                                 #  Domain == "Course of non-bipolar psychiatric illness" & level3 == 'CoNBDpi Other' ~ "CoNBDpi O.",
                                                 # Domain == "Metadata" & level3 == 'Metadata Other' ~ "Metadata O.",
                                                #   Domain == "Current pharmacological treatment" & level3 == 'C PT Other' ~ "C PT O.",
                                                   Domain == "Physiological" & level2 == 'Physical Measurements' ~ "C PT O.",
                                                   TRUE ~level2))%>% mutate(level3 = str_replace_all(level3, "/", " "), 
                                                                           level2 = str_replace_all(level2, "/", " "), 
                                                                           Domain = str_replace_all(Domain, "/", " ")) %>%
  
                                                                    mutate(level3 = str_replace_all(level3, " ", "_"), 
                                                                           level2 = str_replace_all(level2, " ", "_"), 
                                                                           Domain = str_replace_all(Domain, " ", "_")) %>% distinct()
inflam_combined_n$level0 <- rep("Var", dim(inflam_combined_n)[1])

inflam_combined_n$pathString <- paste5(inflam_combined_n$level0, 
                            inflam_combined_n$Domain, 
                            inflam_combined_n$level2, 
                            inflam_combined_n$level3,
                            sep = "/", na.rm=TRUE
                            )  
inflam_combined_n <-  inflam_combined_n %>% arrange(Domain, level2, level3)
 
inflam_ontology <- as.Node( inflam_combined_n) # create data.tree, 102 rows

# https://rdrr.io/cran/data.tree/man/as.igraph.Node.html data.tree --> igraph keep vertex size info
print(inflam_ontology, "mycol")

# convert data.tree to igraph obj
inflam_g <- as.igraph(inflam_ontology, direction = "climb")  %>% delete_vertices("Var")  # %>%  delete_edges( c(1:10))  - can be used to delete vertices with string NA
 
inflam_code_temp <- inflam_combined_n %>% 
   arrange(Domain, level2) %>% 
   mutate(l1_id = (factor(Domain))) # factor the domain name to show it as legend names and color vars by the domain it belongs to
 
inflam_code_temp <- bind_rows(inflam_code_temp[c("Domain", "l1_id")], inflam_code_temp[c( "level2" ,"l1_id")], inflam_code_temp[c("level3","l1_id")]) # create new df grouped by the domain
membership_custom <- cbind(inflam_code_temp[2], name = do.call(pmax, c(inflam_code_temp[-2], na.rm = TRUE))) %>% distinct() %>% drop_na()  %>% arrange(name) # group l2 and l3 variables under l1

### Combine level 2 and level 3 variables into one single column 
a <- cbind(inflam_combined_n[2:3], name = do.call(pmax, c(inflam_combined_n[4], na.rm = TRUE))) %>% na.omit()  %>% ungroup() %>% dplyr::select(level3, name)   
colnames(a) <- c("name", "n")
b <- cbind(inflam_combined_n[2:3], name = do.call(pmax, c(inflam_combined_n[4], na.rm = TRUE)))%>% filter(is.na(level3)) %>% dplyr::select(1,3)
colnames(b) <- c("name", "n")
inflam_combined_level_2_3 <- rbind(a, b)  
```
 
### Convert igraph obj to network d3obj, then use networkd3 functions to manipulate dfs
```{r}

inflam_d3 <- igraph_to_networkD3(inflam_g) # convert igraph obj to networkd3 obj

membership_custom <-  merge(inflam_d3$nodes, membership_custom, on= "name") # merge node df and the new df grouped by domain to get desired color groupings
inflam_d3$nodes <-  membership_custom[match(inflam_d3$nodes$name, membership_custom$name),] # order vars according to the data.tree obj's original order

rnames <- rownames(inflam_d3$nodes)

inflam_d3$nodes$idx <- as.integer(rownames(inflam_d3$nodes))

join_inflam_d3_group_n <- full_join( inflam_d3$nodes, inflam_combined_level_2_3, on = "name")  %>% replace(is.na(.), 0)
inflam_d3$nodes <- merge(inflam_d3$nodes, join_inflam_d3_group_n, by=c("name", "l1_id", "idx"), all.x = TRUE)# %>% dplyr::select()

inflam_d3$nodes <- inflam_d3$nodes[as.integer(rnames), ] # order the rows by the orignal index number order
inflam_d3$nodes$name <- paste0(inflam_d3$nodes$name, ": ", inflam_d3$nodes$n)
 
```

### Use forceNetwork to create networkD3 graph
```{r}
inflam_fn <- forceNetwork(Links = inflam_d3$links, Nodes = inflam_d3$nodes ,
             Source = 'source', Target = 'target', NodeID = 'name',  Group = 'l1_id', # get NodeID and Group from inflam_d3$node
            opacity = 0.9,  zoom = TRUE, legend = TRUE, linkDistance = 10,  
             charge = -50,   # node repulsion   
            Nodesize  = "n" ,
         fontSize = 20, fontFamily = "Calibri" )  
         
htmlwidgets::onRender(inflam_fn, jsCode = ' 
  function (el, x) {
    d3.select("svg").append("g").attr("id", "legend-layer");
    var legend_layer = d3.select("#legend-layer");
    d3.selectAll(".legend")
      .each(function() { legend_layer.append(() => this); }); 
      
  }')   %>% saveNetwork("inflam_net_test.html")
 
 

      
webshot("inflam_net_test.html", "inflam_net_test.jpeg", vwidth = 1700, vheight = 1700, zoom = 1.2) 
 
```
exp