---
title: "Varicat Ontology Viz"
output: html_notebook
---
```{r, message = FALSE}
#install.packages("igraph") 
#install.packages("ggraph") 

# http://curleylab.psych.columbia.edu/netviz/netviz2.html#/20  
```

```{r, message=FALSE}
library(ggraph) 
library(igraph)
library(cli)
library(dplyr)
library(tidyverse) 
library(data.tree) # for making the 'ontology' data structure
library(rlang)
library(networkD3) # for making interactive viz
library(htmltools)
library(stringr)  
library(webshot)
```

```{r, message=FALSE}
# https://stackoverflow.com/questions/13673894/suppress-nas-in-paste
# function to remove NAs and change to ""
paste5 <- function(..., sep = " ", collapse = NULL, na.rm = F) {
  if (na.rm == F)
    paste(..., sep = sep, collapse = collapse)
  else
    if (na.rm == T) {
      paste.na <- function(x, sep) {
        x <- gsub("^\\s+|\\s+$", "", x)
        ret <- paste(na.omit(x), collapse = sep)
        is.na(ret) <- ret == ""
        return(ret)
      }
      df <- data.frame(..., stringsAsFactors = F)
      ret <- apply(df, 1, FUN = function(x) paste.na(x, sep))
      if (is.null(collapse))
        ret
      else {
        paste.na(ret, sep = collapse)
      }
    }
} 
```
 
## Read Ontology file with all varicat vars
```{r}
varicat_ontology <- read.csv("varicat_ontology_full_names.csv", sep=",", header=TRUE)
# reverse order (only relevant for dendogram)
rev_df <- apply(varicat_ontology, 2, rev) # r
 
# converting the result to dataframe
rev_df <- as.data.frame(rev_df) %>% mutate_all(., list(~na_if(.,"")))
rev_df <- as.data.frame(apply(rev_df,2, str_trim)) %>% arrange(level1) # remove trailing spaces
# subset(rev_df,duplicated(level3)) #check if there are duplicats in lvl 3 except for NAs


(unique(varicat_ontology$level1) )# 20
#sort(unique(varicat_ontology$level2) )# 103
#unique(varicat_ontology$level3)
```

### Make ontology with data.tree
```{r}
rev_df <- rev_df %>% dplyr::mutate(level2 = (ifelse(level2 == "Other", paste(level1, level2), level2)), 
                                 level3 = (ifelse(level3 == "Other", paste(level2, level3), level3)), 
                                 level1 = (ifelse(level1 == level2, paste(level1, "Domain"), level1))) %>% mutate(level3 = str_replace_all(level3, "/", "_"), 
                                                                           level2 = str_replace_all(level2, "/", "_"), 
                                                                           level1 = str_replace_all(level1, "/", "_"))   %>% mutate(level3 = 
                                                                                                                              
                                                                          str_replace_all(level3, " ", "_"), 
                                                                           level2 = str_replace_all(level2, " ", "_"), 
                                                                           level1 = str_replace_all(level1, " ", "_"))



# create pathString to make the data tree@
rev_df$pathString <- paste5(rev_df$level0, 
                            rev_df$level1, 
                            rev_df$level2, 
                            rev_df$level3,
                            sep = "/", na.rm=TRUE
                            )  
   

grp <- rev_df %>% group_by(level1) 
ls_dfs <- group_split(grp)  
``` 

### Visualize ontology with ForceNetwork
```{r}

create_fn<- function(rev_df){
  ontology <- as.Node(rev_df, na.rm=TRUE) # create data.tree obj
  g <- as.igraph(ontology, direction = "climb")  %>% delete_vertices("Variable")  #%>%  delete_edges( c(1:10))  - can be used to delete vertices with string NA
  unique(rev_df$level1)
  
  code_temp <- rev_df %>% 
    arrange(level1, level2) %>% 
    mutate(l1_id = (factor(level1))) # factor the domain name to show it as legend names and color vars by the domain it belongs to
  
  code_temp <- bind_rows(code_temp[c(2, 6)], code_temp[c( 3 ,6)], code_temp[c(4,6)]) # create new df grouped by the domain
  membership_custom <- cbind(code_temp[2], name = do.call(pmax, c(code_temp[-2], na.rm = TRUE))) %>% distinct() %>% drop_na()  %>% arrange(name) 
  
  d3 <- igraph_to_networkD3(g)  # convert igraph obj to networkd3 obj for viz
  membership_custom <-  merge(d3$nodes, membership_custom, on= "name") # merge node df and the new df grouped by domain to get desired color groupings
  d3$nodes <-  membership_custom[match(d3$nodes$name, membership_custom$name),] # order vars according to the data.tree obj's original order
  
  # make a grouping variable that will match to colours
 d3$nodes <- d3$nodes %>%
 mutate(color_group = case_when(
    name %in% c("Clinical_characteristics",
    "Cognitive",
    "Clinical_Trial-specific",
    "Course_of_treatment",
    "Course_of_bipolar_illness-episodes",
    "Course_of_bipolar_illness-symptoms",
    "Course_of_non-bipolar_psychiatric_illness",
    "Current_illness_severity",
    "Current_pharmacological_treatment",
    "Demographics",
    "Ecological_Momentary_Assessment",
    "Family_history",
    "Lifetime_pharmacological_treatment",
    "Metadata",
    "Trauma_stress",
    "Physical_health",
    "Non-pharmacological_treatment",
    "Physiological",
    'Miscellaneous_Domain',
    "Positive_psychological_factors") ~ "main",
     TRUE ~ paste0(l1_id, "_sub")
  ))
   return(d3)
}

visualizeDomainNetwork <- function(df) {

   
my_color <- 'd3.scaleOrdinal()
  .domain([
   "Clinical_characteristics_sub", "Cognitive_sub",  "Course_of_bipolar_illness-episodes", "Course_of_bipolar_illness-symptoms_sub", "Course_of_non-bipolar_psychiatric_illness_sub", "Current_illness_severity_sub"   , "Current_pharmacological_treatment_sub", "Demographics_sub", "Ecological_Momentary_Assessment_sub"  , "Family_history_sub"  , "Lifetime_pharmacological_treatment_sub", "Metadata_sub"  ,  "Trauma_stress_sub"  ,  "Physical_health_sub", "Physiological_sub" ,  "Positive_psychological_factors_sub_sub", "Clinical_Trial-specific_sub_sub", "Course_of_treatment_sub",     "Non-pharmacological_treatment_sub", "Miscellaneous_Domain_sub", "main"
  ])
  .range([
     "#7FC07F",  
    "#BEAED4",
    "darkgreen",
    "#C90B20",
    "violet",
    "#F0027F",
    "#BF5B20",
    "#666666",
    "#1B0E77",
    "#D95F00",
    "#7570B3",
    "#E7290A",
    "#66A61E",
    "#E6AA00",
    "#A6761D",
    "#666666",
    "#A6CED3",
    "darkmagenta",
    "#FB9A99",
    "turquoise",
    "black" 
  ])' 

  viz_name <- unique(df$level1)
  d3 <- create_fn(df)
  
# create visualization
fn <- forceNetwork(Links = d3$links, Nodes = d3$nodes ,
             Source = 'source', Target = 'target', NodeID = 'name',  Group = 'l1_id', # get node id and group from d3$node
            opacity = 1,  zoom = TRUE,  linkDistance = 0.0001 , radiusCalculation = 0.01,   #legend = TRUE,
             charge = -70,   # node repulsion 
             fontSize = 20, fontFamily = "Calibri" , colourScale = my_color)


### === CHANGE FILE AND FOLDER NAME === 
filename = paste0("full_ontology/",viz_name,".html")
jpegname = paste0( "full_ontology/", viz_name,".jpeg")
             
clickjs <- "function(el, x) {
  var options = x.options; // Store the options passed from R

  // Select the SVG element
  var svg = d3.select(el).select('svg');

  // Select all nodes and links in the SVG
  var node = svg.selectAll('.node');
  var link = svg.selectAll('link');

  // Store the mouseout event listener for nodes
  var mouseout = d3.selectAll('.node').on('mouseout');

  // Function to calculate the node size based on options
  function nodeSize(d) {
    if (options.nodesize) {
      return eval(options.radiusCalculation);
    } else {
      return 6;
    }
  }

  // Add click event listener to all nodes
  d3.selectAll('.node').on('click', onclick);

  // Function to handle node click events
  function onclick(d) {
    if (d3.select(this).on('mouseout') == mouseout) {
      // If node is not clicked, assign mouseout_clicked event listener
      d3.select(this).on('mouseout', mouseout_clicked);
    } else {
      // If node is clicked, assign regular mouseout event listener
      d3.select(this).on('mouseout', mouseout);
    }
  }

  // Function to handle mouseout event for clicked nodes
  function mouseout_clicked(d) {
    // Reset opacity of nodes and links
    node.style('opacity', +options.opacity);
    link.style('opacity', +options.opacity);

    // Transition the node circle to its original size
    d3.select(this).select('circle').transition()
      .duration(750)
      .attr('r', function(d) { return nodeSize(d); });

    // Transition the node text to its original position and font size
    d3.select(this).select('text').transition()
      .duration(1250)
      .attr('x', 0)
      .style('font', options.fontSize + 'px ');
  }
}"

 
htmlwidgets::onRender(fn, clickjs) %>%  saveNetwork(filename) 

webshot(filename, jpegname, vwidth = 400, vheight = 400, zoom = 0.8) 

}

 
for(i in 2:length(ls_dfs)-1) {
 visualizeDomainNetwork(ls_dfs[[i]] )
}
```

### ==== ARCHIVED VISUALIZATIONS === 
```{r}
code_temp <- rev_df %>% 
   arrange(level1, level2) %>% 
   mutate(l1_id = (factor(level1))) # factor the domain name to show it as legend names and color vars by the domain it belongs to

code_temp <- bind_rows(code_temp[c(2, 6)], code_temp[c( 3 ,6)], code_temp[c(4,6)]) # create new df grouped by the domain
membership_custom <- cbind(code_temp[2], name = do.call(pmax, c(code_temp[-2], na.rm = TRUE))) %>% distinct() %>% drop_na()  %>% arrange(name) 

d3 <- igraph_to_networkD3(g)  # convert igraph obj to networkd3 obj for viz
membership_custom <-  merge(d3$nodes, membership_custom, on= "name") # merge node df and the new df grouped by domain to get desired color groupings
d3$nodes <-  membership_custom[match(d3$nodes$name, membership_custom$name),] # order vars according to the data.tree obj's original order

my_color <- 'd3.scaleOrdinal() .domain(["Clinical_characteristics", "Cognitive" , "Course_of_bipolar_illness-episodes"   ,    
   "Course_of_bipolar_illness-symptoms", "Course_of_non-bipolar_psychiatric_illness", "Current_illness_severity"   ,              
  "Current_pharmacological_treatment", "Demographics", "Ecological_Momentary_Assessment"  , "Family_history"  , "Lifetime_pharmacological_treatment", 
  "Metadata"  ,  "Trauma_stress"  ,  "Physical_health", "Physiological" ,  "Positive_psychological_factors", "Clinical_Trial-specific", "Course_of_treatment"]) .range(["#7FC07F" , "#BEAED4" ,"darkgreen" ,"#C90B20", "violet" ,
 "#F0027F" ,"#BF5B20" ,"#666666" ,"#1B0E77" ,"#D95F00" ,
"#7570B3" ,"#E7290A", "#66A61E" ,"#E6AA00" ,"#A6761D" ,
"#666666" ,"#A6CED3", "darkmagenta"  ,"#FB9A99",  "turquoise" ])' 


#webshot("varicat_ontology.html", "varicat_ontology.jpeg", vwidth = 1700, vheight = 1700, zoom = 1.2) 
```

### Inflammaging dataset
```{r}
#### Reshape Inflammaging df to conform to ontology 
inflam <- read.csv("inflammaging_varicat.csv", sep=",", header=TRUE)

colnames_inflam <- colnames(inflam) # get col names 
inflam_subset_cols <- colnames_inflam[lapply(colnames_inflam, function(x) length(grep("Please|Is.this|What" ,x,value=FALSE))) == 0] # remove sublevels that are too low in the tree
inflam <- inflam %>% dplyr::select(inflam_subset_cols) %>%  select(-(last_col(offset = 5):last_col()))  %>% 
  select(-head(names(.), 5)) # remove first and last five cols

inflam <- mutate_all(inflam, list(~na_if(.,""))) # remove "" and replace as NAs
num_var_per_level <- data.frame(colSums(!is.na(inflam ))) # how many variables are there in each level? (e.g., in  Physical health -> Physical Measurements ->	Weight)

num_var_per_level<- cbind(rownames(num_var_per_level), data.frame(num_var_per_level, row.names=NULL)) # remove row index, create row index as new col
colnames(num_var_per_level) <- c("old_names", "num_var") # rename cols

inflam_2_cols <- cbind(inflam[1], mycol = do.call(pmax, c(inflam[-1], na.rm = TRUE))) %>% group_by(mycol) %>% arrange(Domain.Main.category.of.the.variable.) #collapse mult columns into 1
colnames(inflam)
# inflam_subSet %>% dplyr::select(Comorbidities.type., Physical.health.type.) %>% filter(Physical.health.type. == "Comorbidities", !is.na(Comorbidities.type.)) # 120 vars
# inflam_subSet %>% dplyr::select(Comorbidities.type., Physical.health.type.) %>% filter(Physical.health.type. == "Comorbidities", is.na(Comorbidities.type.)) # 31 vars 

inflam %>% group_by(Type.of.clinical.characteristics.) %>% filter(!is.na(Type.of.clinical.characteristics.)) %>%  select_if(~any(!is.na(.)))
inflam %>% group_by(Course.of.bipolar.illness.symptoms.type.) %>% filter(!is.na(Course.of.bipolar.illness.symptoms.type.)) %>%  select_if(~any(!is.na(.))) %>% arrange(Course.of.bipolar.illness.symptoms.type.)
redcap_output <-  read.csv("redcap_output_colnames.csv")
l1_exist_in_inflam <- unique(redcap_output$level1)[unique(redcap_output$level1) %in% colnames(inflam)]
l2_exist_in_inflam <- unique(redcap_output$level2)[unique(redcap_output$level2) %in% colnames(inflam)]
l3_exist_in_inflam <- unique(redcap_output$level3)[unique(redcap_output$level3) %in% colnames(inflam)]

```

### Data cleaning for inflammaging dataset to create entire Inflammaging ontology
```{r}
all_levels<-read.csv("all_levels_names.csv") 

# check level names in inflam dataset that do not belong to any levels ontology (this is weird, need to check)
inflam_2_cols[!inflam_2_cols$mycol %in% c(all_levels$level2) & 
                 !inflam_2_cols$mycol %in% c(all_levels$level3),] %>% group_by(mycol) %>% tally() 
inflam_2_cols <- inflam_2_cols [!inflam_2_cols$mycol %in% c("Drug name", "Miscellaneous", "Number of conditions", "Severity score"), ]

#inflam_2_cols%>% group_by(Domain.Main.category.of.the.variable., mycol) %>% tally()  #=== THIS IS CORRECT ====

inflam_2_cols <- inflam_2_cols %>% mutate(Domain.Main.category.of.the.variable.=  case_when(mycol == "Physical Measurements" & Domain.Main.category.of.the.variable. == "Physiological" ~ "Physical health", 
                                                                                            TRUE ~ Domain.Main.category.of.the.variable. ))   
 
# looks like these levels are actually level 4 categories -> remove them 
# group by level2 and 3 names and count the number vars in each of levels 
inflam <- inflam_2_cols [!inflam_2_cols$mycol %in% c("Drug name", "Miscellaneous", "Number of conditions", "Severity score"), ] %>% group_by(Domain.Main.category.of.the.variable., mycol) %>% mutate(n= n()) %>% arrange(Domain.Main.category.of.the.variable.)  %>% distinct()

only_level_2 <- inflam[inflam$mycol %in%c(all_levels$level2), ]
only_level_3 <- inflam[inflam$mycol %in%c(all_levels$level3), ]

colnames(only_level_2) <- c("Domain", "level2", "level2_n")
colnames(only_level_3) <- c("Domain", "level3", "level3_n")
# separate level 2 and 3 into different columns
inflam_level_2_3_split <- rbind(only_level_2, only_level_3)

Current_diagnosis_sublevels <- c('Diagnostic group (e.g., Bipolar vs other psychiatric diagnosis or HC)',
  'Other diagnostic specifiers', 
  'Current episode type (e.g., manic/depressed/euthymic/mixed/remitted)', 
  'Most recent affective episode type')
global <- c('Global/screening score')
dep_eps_course <- c('History of psychotic depression', 'History of depression with atypical symptoms', 'Number of depressive episodes')
manic_eps_course <- c('Number of manic episodes')
hypomanic_eps_course <-  c('Number of hypomanic episodes')
mixed_eps_course <- c('Number of mixed episodes')
general_eps_features <- c('Lifetime rapid cycling', 'Seasonality?')
hopsitalizations <- c('Number of psychiatric hospitalizations')
functioning <- c('Rated by others')
c_drug_class <- c('Total psychiatric medications (count)',  'Non-Psychiatric Medications')
ect <- c('Lifetime number of ECTs')
phys_measure <- c('Weight')
comorbidities  <- c('Heart', 'Vascular', 'Renal','Endocrine and breast', 'Respiratory', 'Eyes/ears/ nose/ throat/ and larynx', 'Musculoskeletal and skin', 'Neurologic', 'Liver/pancreas/ and biliary', 'Upper GI','Lower GI', 'Hematopoietic', 'Genitourinary') 

inflam_level_2_3_split <- inflam_level_2_3_split %>% mutate(level2 = case_when(
  level3 %in% Current_diagnosis_sublevels  ~ "Current diagnosis", 
  level3 %in% global ~ "Global",
  level3 %in% dep_eps_course ~ "Depressive episode course",
  level3 %in% manic_eps_course ~ "Manic episode course",
  level3 %in% hypomanic_eps_course ~ "Hypomanic episode course",
  level3 %in% mixed_eps_course ~ "Mixed episode course",
  level3 %in% general_eps_features ~ "General episodic features",
  level3 %in% hopsitalizations ~ "Hopsitalizations",
  level3 %in% functioning ~ "Functioning",
  level3 %in% c_drug_class ~ "Drug class",
  level3 %in% ect ~ "ECT",
   level3 %in% phys_measure ~ "Physical Measurements",
  level3 %in% comorbidities ~ "Comorbidities",
  TRUE ~ level2))
```

### Visualize entire inflammaging ontology with ForceNetwork
```{r}
inflam_combined_n <- cbind(inflam_level_2_3_split[c(1,2,4)], mycol = do.call(pmax, c(inflam_level_2_3_split['level2_n'] , inflam_level_2_3_split['level3_n'], na.rm = TRUE))) %>% arrange(Domain)
inflam_combined_n <- inflam_combined_n %>% mutate(level2 = case_when(Domain == 'Current pharmacological treatment' & level3 == 'Total psychiatric medications (count)' ~ "Current Drug Class",
                                                Domain == 'Current pharmacological treatment' & level3 == 'Non-Psychiatric Medications' ~ "Current Drug Class",
                                                 Domain == 'Current pharmacological treatment' & level2 == 'Drug class' & is.na(level3) ~ "Current Drug Class",
                                                TRUE ~level2)) %>% mutate(level3 = case_when(
                                                  Domain == "Course of non-bipolar psychiatric illness" & level3 == 'Other' ~ "CoNBDpi Other",
                                                  Domain == "Metadata" & level3 == 'Other' ~ "Metadata Other",
                                                  Domain == "Current pharmacological treatment" & level3 == 'Other' ~ "C PT Other",
                                                   TRUE ~level3)) %>% mutate(level2 = case_when(
                                                  Domain == "Course of non-bipolar psychiatric illness" & level3 == 'CoNBDpi Other' ~ "CoNBDpi O.",
                                                  Domain == "Metadata" & level3 == 'Metadata Other' ~ "Metadata O.",
                                                  Domain == "Current pharmacological treatment" & level3 == 'C PT Other' ~ "C PT O.",
                                                   Domain == "Physiological" & level2 == 'Physical Measurements' ~ "C PT O.",
                                                   TRUE ~level2))%>% mutate(level3 = str_replace_all(level3, "/", " "), 
                                                                           level2 = str_replace_all(level2, "/", " "), 
                                                                           Domain = str_replace_all(Domain, "/", " ")) %>% distinct()
inflam_combined_n$level0 <- rep("Var", dim(inflam_combined_n)[1])

inflam_combined_n$pathString <- paste5(inflam_combined_n$level0, 
                            inflam_combined_n$Domain, 
                            inflam_combined_n$level2, 
                            inflam_combined_n$level3,
                            sep = "/", na.rm=TRUE
                            )  
inflam_combined_n <-  inflam_combined_n %>% arrange(Domain, level2, level3)
inflam_combined_n   %>% arrange(level2, level3)
#inflam_ontology <- FromDataFrameTable(inflam_combined_n, colLevels = list( c("mycol")), na.rm = TRUE)
inflam_ontology <- as.Node( inflam_combined_n)

# https://rdrr.io/cran/data.tree/man/as.igraph.Node.html data.tree --> igraph keep vertex size info
print(inflam_ontology, "mycol")

inflam_g <- as.igraph(inflam_ontology, direction = "climb")  %>% delete_vertices("Var")  #%>%  delete_edges( c(1:10))  - can be used to delete vertices with string NA

inflam_code_temp <- inflam_combined_n %>% 
   arrange(Domain, level2) %>% 
   mutate(l1_id = (factor(Domain))) # factor the domain name to show it as legend names and color vars by the domain it belongs to


inflam_code_temp <- bind_rows(inflam_code_temp[c("Domain", "l1_id")], inflam_code_temp[c( "level2" ,"l1_id")], inflam_code_temp[c("level3","l1_id")]) # create new df grouped by the domain
membership_custom <- cbind(inflam_code_temp[2], name = do.call(pmax, c(inflam_code_temp[-2], na.rm = TRUE))) %>% distinct() %>% drop_na()  %>% arrange(name) 

inflam_d3 <- igraph_to_networkD3(inflam_g)
membership_custom <-  merge(inflam_d3$nodes, membership_custom, on= "name") # merge node df and the new df grouped by domain to get desired color groupings
inflam_d3$nodes <-  membership_custom[match(inflam_d3$nodes$name, membership_custom$name),] # order vars according to the data.tree obj's original order
 

inflam_fn <- forceNetwork(Links = inflam_d3$links, Nodes = inflam_d3$nodes ,
             Source = 'source', Target = 'target', NodeID = 'name',  Group = 'l1_id', # get node id and group from d3$node
            opacity = 0.9,  zoom = TRUE, legend = TRUE, linkDistance = 25, radiusCalculation = 1.5, 
             charge = -15,   # node repulsion 
             fontSize = 25, fontFamily = "Calibri", Nodesize = 1
             ) 

 inflam_fn %>% saveNetwork("inflam_net.html")
 
V(inflam_g)
```
